
const S={home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5 10.5V20h14v-9.5"/><path d="M9.5 20v-6h5v6"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14"/><path d="M5 12h14"/></svg>',file:'<svg viewBox="0 0 24 24"><path d="M7 3h7l4 4v14H7z"/><path d="M14 3v5h5"/><path d="M9 13h6"/><path d="M9 17h6"/></svg>',chart:'<svg viewBox="0 0 24 24"><path d="M4 19V5"/><path d="M4 19h17"/><path d="M8 16v-5"/><path d="M13 16V8"/><path d="M18 16v-9"/></svg>',settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a8 8 0 0 0 .1-2l2-1.5-2-3.5-2.4 1a7 7 0 0 0-1.7-1l-.3-2.6H9l-.3 2.6a7 7 0 0 0-1.7 1l-2.4-1-2 3.5 2 1.5a8 8 0 0 0 .1 2l-2 1.5 2 3.5 2.4-1a7 7 0 0 0 1.7 1l.3 2.6h6.2l.3-2.6a7 7 0 0 0 1.7-1l2.4 1 2-3.5z"/></svg>',bell:'<svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 7h18s-3 0-3-7"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',food:'<svg viewBox="0 0 24 24"><path d="M6 3v8"/><path d="M10 3v8"/><path d="M8 3v18"/><path d="M4 11h8"/><path d="M17 3v18"/><path d="M17 3c2.5 1.5 3.5 4 3.5 7 0 2-1.5 3-3.5 3"/></svg>',bag:'<svg viewBox="0 0 24 24"><path d="M6 8h12l1 13H5z"/><path d="M9 8a3 3 0 0 1 6 0"/></svg>',bus:'<svg viewBox="0 0 24 24"><path d="M6 4h12a2 2 0 0 1 2 2v9a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V6a2 2 0 0 1 2-2z"/><path d="M4 10h16"/><path d="M8 18l-2 3"/><path d="M16 18l2 3"/><circle cx="8" cy="14" r="1"/><circle cx="16" cy="14" r="1"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.8 5.6a5.4 5.4 0 0 0-7.6 0L12 6.8l-1.2-1.2a5.4 5.4 0 1 0-7.6 7.6L12 22l8.8-8.8a5.4 5.4 0 0 0 0-7.6z"/></svg>',game:'<svg viewBox="0 0 24 24"><path d="M7 9h10a5 5 0 0 1 4.7 6.7l-.6 1.8a2.2 2.2 0 0 1-3.7.8L15 16H9l-2.4 3.3a2.2 2.2 0 0 1-3.7-.8l-.6-1.8A5 5 0 0 1 7 9z"/><path d="M8 12v4"/><path d="M6 14h4"/><path d="M16 13h.01"/><path d="M18 15h.01"/></svg>',lipstick:'<svg viewBox="0 0 24 24"><path d="M9 11h6v10H9z"/><path d="M10 7l4-4 1 8H9z"/><path d="M8 21h8"/></svg>',shield:'<svg viewBox="0 0 24 24"><path d="M12 3 20 6v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/><path d="M12 8v8"/><path d="M8 12h8"/></svg>',book:'<svg viewBox="0 0 24 24"><path d="M4 5a3 3 0 0 1 3-3h13v17H7a3 3 0 0 0-3 3z"/><path d="M4 5v17"/><path d="M8 6h8"/></svg>',dots:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg>'};
const cats=[['食費','food','#0f9864'],['日用品','bag','#f59e0b'],['交通費','bus','#0aa174'],['交際費','heart','#f55772'],['娯楽・趣味','game','#7c5ce1'],['美容・衣服','lipstick','#ef476f'],['医療・保険','shield','#1698a8'],['教育・学習','book','#369bd6'],['その他','dots','#999']];
const yen=n=>'¥'+Math.round(Number(n||0)).toLocaleString('ja-JP'), ym=(d=new Date())=>d.toISOString().slice(0,7), today=()=>new Date().toISOString().slice(0,10);
let mon=ym(), sel='食費', graph='pie', st=load();
function load(){try{let x=JSON.parse(localStorage.getItem('kakeibo-final-real-v3')||localStorage.getItem('kakeibo-svg-v1')||'null'); if(x){x.meta=x.meta||x.categoriesMeta||cats.map(([name,icon,color])=>({name,icon,color}));x.months=x.months||{};x.expenses=x.expenses||[];return x}}catch{} return {meta:cats.map(([name,icon,color])=>({name,icon,color})),months:{},expenses:[]}}
function save(){localStorage.setItem('kakeibo-final-real-v3',JSON.stringify(st))}
function names(){return st.meta.map(x=>x.name)} function mt(n){return st.meta.find(x=>x.name===n)||st.meta.at(-1)}
function soft(hex){let c=hex.replace('#',''),r=parseInt(c.slice(0,2),16),g=parseInt(c.slice(2,4),16),b=parseInt(c.slice(4,6),16);return `rgba(${r},${g},${b},.12)`}
function ensure(m){if(!st.months[m])st.months[m]={income:0,budgets:{}};names().forEach(c=>{if(st.months[m].budgets[c]===undefined)st.months[m].budgets[c]=0})}
function ex(m){return st.expenses.filter(e=>e.date&&e.date.startsWith(m))} function spent(m,c){return ex(m).filter(e=>e.category===c).reduce((s,e)=>s+Number(e.amount||0),0)} function total(m){return ex(m).reduce((s,e)=>s+Number(e.amount||0),0)}
function cls(b,u){if(!b)return'safe';let r=u/b;return r>=1?'over':r>=.9?'danger':r>=.7?'warn':'safe'}
function mount(){bell.innerHTML=S.bell;search.innerHTML=S.search;nHome.insertAdjacentHTML('afterbegin',S.home);nPlus.insertAdjacentHTML('afterbegin',S.plus);nFile.insertAdjacentHTML('afterbegin',S.file);nChart.insertAdjacentHTML('afterbegin',S.chart);nSet.insertAdjacentHTML('afterbegin',S.settings)}
document.addEventListener('click',e=>{let p=e.target.closest('[data-page]');if(p)page(p.dataset.page);let c=e.target.closest('[data-cat]');if(c)detail(c.dataset.cat);if(e.target.closest('[data-close]'))closeM();let t=e.target.closest('[data-graph]');if(t){graph=t.dataset.graph;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.graph===graph));drawGraph()}});
function page(id){closeM();document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));render();scrollTo({top:0,behavior:'smooth'})}
date.value=today();histMonth.value=mon;setMonth.value=mon;
form.onsubmit=e=>{e.preventDefault();let a=Number(amount.value),d=date.value||today(),m=memo.value.trim();if(!a)return msg.textContent='金額を入力してね';st.expenses.push({id:String(Date.now()),date:d,amount:a,category:sel,memo:m});mon=d.slice(0,7);save();amount.value='';memo.value='';msg.textContent='保存しました';setTimeout(()=>msg.textContent='',1200);render()}
;[histMonth,histCat,keyword].forEach(el=>el.oninput=renderHist);prevM.onclick=()=>{histMonth.value=shift(histMonth.value||mon,-1);renderHist()};nextM.onclick=()=>{histMonth.value=shift(histMonth.value||mon,1);renderHist()}
function shift(m,d){let [y,mo]=m.split('-').map(Number);return ym(new Date(y,mo-1+d,1))}
saveSettings.onclick=()=>{let m=setMonth.value||mon;ensure(m);st.months[m].income=Number(income.value||0);names().forEach(c=>{let i=document.querySelector(`[data-budget="${CSS.escape(c)}"]`);st.months[m].budgets[c]=Number(i?.value||0)});mon=m;save();render()}
export.onclick=()=>{let b=new Blob([JSON.stringify(st,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='kakeibo-backup.json';a.click()}
import.onchange=async e=>{let f=e.target.files[0];if(!f)return;st=JSON.parse(await f.text());save();render()}
function render(){ensure(mon);renderHome();renderInput();renderHist();renderSet();drawGraph()}
function renderHome(){balance.textContent=yen(Number(st.months[mon].income||0)-total(mon));monthNow.textContent=mon.replace('-','年')+'月';catCards.innerHTML=names().map(c=>{let m=mt(c),b=Number(st.months[mon].budgets[c]||0),u=spent(mon,c),l=b-u,r=b?u/b:0,cl=cls(b,u);return `<article class="catCard ${cl}" data-cat="${c}"><div class="catMain"><div class="catIcon" style="color:${m.color};background:${soft(m.color)}">${S[m.icon]||S.dots}</div><div><div class="catName">${c}</div><div class="catLeft">${yen(l)}</div></div><div class="chev">›</div></div><div class="progress"><span style="width:${Math.min(r*100,100)}%"></span></div><div class="meta"><span>予算 ${yen(b)}</span><span>使った額 ${yen(u)}</span><span>${Math.round(r*100)}%</span></div></article>`}).join('');recent.innerHTML=ex(mon).slice(-4).reverse().map(row).join('')||'<p>まだ支出がありません</p>'}
function row(e){let m=mt(e.category);return `<div class="row"><div class="catIcon" style="color:${m.color};background:${soft(m.color)}">${S[m.icon]||S.dots}</div><div><strong>${e.category}</strong><small>${e.memo||'メモなし'}　${e.date}</small></div><strong>${yen(e.amount)}</strong></div>`}
function renderInput(){picker.innerHTML=names().map(c=>{let m=mt(c);return `<button type="button" class="pick ${c===sel?'active':''}" data-pick="${c}"><span class="pickIcon" style="color:${m.color}">${S[m.icon]||S.dots}</span><span>${c}</span></button>`}).join('');document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{sel=b.dataset.pick;renderInput()})}
function renderHist(){let m=histMonth.value||mon;ensure(m);let ca=histCat.value,kw=keyword.value.trim();histSpent.textContent=yen(total(m));histIncome.textContent=yen(st.months[m].income||0);histCat.innerHTML='<option value="">すべて</option>'+names().map(c=>`<option value="${c}">${c}</option>`).join('');histCat.value=ca;let arr=ex(m);if(ca)arr=arr.filter(e=>e.category===ca);if(kw)arr=arr.filter(e=>(e.memo||'').includes(kw));historyList.innerHTML=arr.slice().reverse().map(row).join('')||'<p>該当する支出がありません</p>'}
function renderSet(){ensure(mon);setMonth.value=mon;income.value=st.months[mon].income||0;budgets.innerHTML=names().map(c=>{let m=mt(c);return `<div class="budgetRow"><strong><span style="color:${m.color};display:inline-block;width:20px;vertical-align:middle">${S[m.icon]||S.dots}</span> ${c}</strong><input data-budget="${c}" type="number" inputmode="numeric" value="${st.months[mon].budgets[c]||0}"></div>`}).join('')}
function detail(c){sel=c;let b=Number(st.months[mon].budgets[c]||0),u=spent(mon,c),l=b-u,r=b?u/b:0,items=ex(mon).filter(e=>e.category===c).slice().reverse();detailTitle.textContent=c;detail.innerHTML=`<section class="detailHero"><p>今月の残り予算</p><div class="catLeft">${yen(l)}</div><p>予算 ${yen(b)}　残り ${Math.max(0,Math.round((1-r)*100))}%</p><div class="progress safe"><span style="width:${Math.min(r*100,100)}%"></span></div></section><div class="stats"><div class="stat"><span>平均/日</span><strong>${yen(u/Math.max(1,new Date().getDate()))}</strong></div><div class="stat"><span>使った金額</span><strong>${yen(u)}</strong></div><div class="stat"><span>残り</span><strong>${yen(l)}</strong></div></div><section class="card"><div class="title in"><h2>最近の支出</h2><button data-page="history">すべて見る</button></div>${items.map(row).join('')||'<p>このカテゴリの支出はまだありません</p>'}</section>`;modal.hidden=false}
function closeM(){modal.hidden=true}
function setup(id){let cv=document.getElementById(id);if(!cv)return null;let r=cv.getBoundingClientRect(),d=Math.max(devicePixelRatio||1,2),w=Math.max(280,r.width),h=Math.max(300,r.height||360);cv.width=w*d;cv.height=h*d;let ctx=cv.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);return{ctx,w,h}}
function text(ctx,t,x,y,s=14,c='#111',wt='700',align='left'){ctx.fillStyle=c;ctx.font=`${wt} ${s}px -apple-system,BlinkMacSystemFont,sans-serif`;ctx.textAlign=align;ctx.fillText(t,x,y);ctx.textAlign='left'}
function drawGraph(){if(!graphTitle)return;if(graph==='pie'){graphTitle.textContent='カテゴリ別 支出割合';pie()}else if(graph==='stack'){graphTitle.textContent='月別 支出の推移';stack()}else{graphTitle.textContent=`${sel}の推移`;trend('graph',sel)}}
function pie(){let c=setup('graph');if(!c)return;let{ctx,w,h}=c,vals=names().map(n=>spent(mon,n)),tot=vals.reduce((a,b)=>a+b,0);if(!tot){text(ctx,'データなし',w/2,h/2,16,'#777','700','center');return}let compact=w<500,r=compact?Math.min(w*.28,105):Math.min(w*.23,120),cx=compact?w/2:r+35,cy=compact?145:h*.43,start=-Math.PI/2;vals.forEach((v,i)=>{if(!v)return;let a=v/tot*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,start,start+a);ctx.fillStyle=mt(names()[i]).color;ctx.fill();start+=a});ctx.beginPath();ctx.arc(cx,cy,r*.48,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();text(ctx,'合計',cx,cy-7,13,'#777','800','center');text(ctx,yen(tot),cx,cy+22,20,'#111','900','center');let lx=compact?24:cx+r+35,ly=compact?cy+r+50:cy-r+20;names().forEach((n,i)=>{if(!vals[i])return;let y=ly+i*31;if(y>h-10)return;let m=mt(n);ctx.fillStyle=m.color;ctx.beginPath();ctx.arc(lx,y-5,6,0,Math.PI*2);ctx.fill();text(ctx,n,lx+18,y,13,'#222','800');text(ctx,`${Math.round(vals[i]/tot*1000)/10}%`,w-32,y,13,'#777','800','right')})}
function stack(){let c=setup('graph');if(!c)return;let{ctx,w,h}=c,year=mon.slice(0,4),left=42,right=12,top=38,bottom=105,cw=w-left-right,ch=h-top-bottom,months=Array.from({length:12},(_,i)=>`${year}-${String(i+1).padStart(2,'0')}`),totals=months.map(m=>total(m)),max=Math.max(...totals,1);grid(ctx,left,top,cw,ch);let gap=cw/12,bw=Math.min(24,gap*.56);months.forEach((m,i)=>{let x=left+gap*i+(gap-bw)/2,y=top+ch;names().forEach(n=>{let v=spent(m,n);if(!v)return;let bh=v/max*ch;y-=bh;ctx.fillStyle=mt(n).color;round(ctx,x,y,bw,bh,5)});text(ctx,`${i+1}月`,x+bw/2,h-78,11,'#777','700','center')});let lx=18,ly=h-50;names().slice(0,6).forEach((n,i)=>{let x=lx+(i%3)*120,y=ly+Math.floor(i/3)*24,m=mt(n);ctx.fillStyle=m.color;ctx.beginPath();ctx.arc(x,y-5,5,0,Math.PI*2);ctx.fill();text(ctx,n,x+10,y,12,'#333','700')})}
function trend(id,cat){let c=setup(id);if(!c)return;let{ctx,w,h}=c,year=mon.slice(0,4),vals=Array.from({length:12},(_,i)=>spent(`${year}-${String(i+1).padStart(2,'0')}`,cat)),max=Math.max(...vals,1),l=36,r=14,t=28,b=34,cw=w-l-r,ch=h-t-b;grid(ctx,l,t,cw,ch);ctx.strokeStyle=mt(cat).color;ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{let x=l+cw*i/11,y=t+ch-v/max*ch;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y)});ctx.stroke()}
function grid(ctx,l,t,w,h){ctx.strokeStyle='#e9eee9';ctx.lineWidth=1;for(let i=0;i<=4;i++){let y=t+h*i/4;ctx.beginPath();ctx.moveTo(l,y);ctx.lineTo(l+w,y);ctx.stroke()}}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();ctx.fill()}
addEventListener('resize',()=>setTimeout(render,80)); if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js'); mount(); render();
